Added missing library.json build flag (#269)
Project wouldn't compile with this error:
.pio/libdeps/esp32cam/esp32-camera/driver/cam_hal.c:18:10: fatal error: ll_cam.h: No such file or directory
Adding this line seems to fix it.